#!/usr/bin/env bash
# script to dig subdomain records for the domain specified
# shellcheck disable=SC2086

function get_a_records() {
    if [[ -n "$2" ]]; then
        # Query a specific subdomain
        response="$(dig +short "$2.$1" | grep -m 1 '^[0-9]')"
        if [[ -n "$response" ]]; then
            record_type="A"
            echo "The subdomain $2 is a $record_type record and points to $response"
        else
            echo "No A record found for $2.$1"
        fi
    else
        # Query default subdomains
        subdomains=(www lb-01 web-01 web-02)
        for sub_d in "${subdomains[@]}"; do
            response="$(dig +short "$sub_d.$1" | grep -m 1 '^[0-9]')"
            if [[ -n "$response" ]]; then
                record_type="A"
                echo "The subdomain $sub_d is a $record_type record and points to $response"
            else
                echo "No A record found for $sub_d.$1"
            fi
        done
    fi
}

# Run the function with provided arguments
get_a_records "$1" "$2"
